### ISSUE TITLE
Crash with K2 when K2 containers are disabled

### ISSUE THREAD

**Issue by GeneralTanker** [nicolas-lang/Factorio.SmallTank#2]
As title say if the option for enabling the K2 containers is unchecked the game crashes on load.

**Comment by nicolas-lang** [comment]
It would save me some time if you cold provide the error message related to the crash from the [factorio log](https://wiki.factorio.com/Log_file)

**Comment by nicolas-lang** [comment]
Nevermind, I was able to replicate the issue myself :-)

**Comment by nicolas-lang** [comment]
Fixed with most recent release, please confirm it is working for you.
